### Health check
GET http://localhost:3000/health

###

### Create workout
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json

{
  "name": "Push Day A"
}

###

### Create workout - validation test (should return 400)
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json

{
  "name": ""
}

###

### Get all workouts
GET http://localhost:3000/api/v1/workouts

###

### Get single workout
GET http://localhost:3000/api/v1/workouts/08bef391-a97f-460e-b43b-5424387460ab

###

### Get single workout - fake ID (should return 404)
GET http://localhost:3000/api/v1/workouts/00000000-0000-0000-0000-000000000000

###

### Log a set
POST http://localhost:3000/api/v1/workouts/08bef391-a97f-460e-b43b-5424387460ab/sets
Content-Type: application/json

{
  "set_number": 1,
  "actual_weight_kg": 100,
  "actual_reps": 8,
  "rpe": 7.5
}

###

### Get workout with sets
GET http://localhost:3000/api/v1/workouts/08bef391-a97f-460e-b43b-5424387460ab


POST http://localhost:3000/api/v1/workouts/08bef391-a97f-460e-b43b-5424387460ab/sets
Content-Type: application/json

{
  "exercise_id": "3f3f0f18-3158-4761-8c65-6fde8ad3ebbe",
  "set_number": 1,
  "actual_weight_kg": 100,
  "actual_reps": 8,
  "rpe": 7.5
}